### PR TITLE
Moved files from arfc/serpent-input to arfc/msr-neutronics

### PR DESCRIPTION
**Pull request by ZoeRichter**
I preserved history when I made the move.  I didn't include the CANDU directory, only the two directories for MSRs.

### CODE REVIEW

**Comment by smpark7** [comment]
Should be fine to merge after we include a brief README that they are msre/cammi designs by Alex Lindsay?

**Comment by katyhuff** [comment]
@ZoeRichter : Can you please add readme's as suggested by @smpark7 ?

**Comment by ZoeRichter** [comment]
I've added a short readme to the msr-th-u directory.

**Comment by katyhuff** [comment]
image

**Pull request merged**
